//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SimpleSlide {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "18.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Strings {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Strings() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("SimpleSlide.Strings", typeof(Strings).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Continue slide show (P).
        /// </summary>
        internal static string ContinueTT {
            get {
                return ResourceManager.GetString("ContinueTT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Continuing....
        /// </summary>
        internal static string Continuing {
            get {
                return ResourceManager.GetString("Continuing", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Continue.
        /// </summary>
        internal static string ContiueStr {
            get {
                return ResourceManager.GetString("ContiueStr", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Delay.
        /// </summary>
        internal static string Delay {
            get {
                return ResourceManager.GetString("Delay", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Moving to next folder.
        /// </summary>
        internal static string FolderNext {
            get {
                return ResourceManager.GetString("FolderNext", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to _N files and folders for next folder. XBox is slow with these things. Hang on....
        /// </summary>
        internal static string FolderPrepXBox {
            get {
                return ResourceManager.GetString("FolderPrepXBox", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Moving to previous folder.
        /// </summary>
        internal static string FolderPrev {
            get {
                return ResourceManager.GetString("FolderPrev", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Restarting from last time....
        /// </summary>
        internal static string FromLastTime {
            get {
                return ResourceManager.GetString("FromLastTime", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Restarting from last time. XBox can be slow with this. Hang on....
        /// </summary>
        internal static string FromLastTimeXBox {
            get {
                return ResourceManager.GetString("FromLastTimeXBox", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ####.
        /// </summary>
        internal static string HashSigns {
            get {
                return ResourceManager.GetString("HashSigns", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .jpeg, .jpg, .png, .bmp, .gif, .tiff, .ico, .svg.
        /// </summary>
        internal static string ImageFileTypes {
            get {
                return ResourceManager.GetString("ImageFileTypes", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Looking for any of these file types: .
        /// </summary>
        internal static string LookingFor {
            get {
                return ResourceManager.GetString("LookingFor", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to There is no media in or under the selected folder &quot;_0.&quot; Try a different folder..
        /// </summary>
        internal static string NoMediaMessage {
            get {
                return ResourceManager.GetString("NoMediaMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No media.
        /// </summary>
        internal static string NoMediaTitle {
            get {
                return ResourceManager.GetString("NoMediaTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No previous session.
        /// </summary>
        internal static string NoPrevious {
            get {
                return ResourceManager.GetString("NoPrevious", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Paused....
        /// </summary>
        internal static string Paused {
            get {
                return ResourceManager.GetString("Paused", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Pause.
        /// </summary>
        internal static string PauseStr {
            get {
                return ResourceManager.GetString("PauseStr", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Pause slide show (P).
        /// </summary>
        internal static string PauseTT {
            get {
                return ResourceManager.GetString("PauseTT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SimpleSlide.json.
        /// </summary>
        internal static string PersistentFname {
            get {
                return ResourceManager.GetString("PersistentFname", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Select a folder to get started.
        /// </summary>
        internal static string SelectFolder {
            get {
                return ResourceManager.GetString("SelectFolder", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Starting....
        /// </summary>
        internal static string Starting {
            get {
                return ResourceManager.GetString("Starting", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Starting. XBox can be slow with this. Hang on....
        /// </summary>
        internal static string StartingXBox {
            get {
                return ResourceManager.GetString("StartingXBox", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .mts, .mp4, .m4v, .mp4v, .3g2, .3gp2, .3gp, .3gpp, .mov, .mpg, .mpeg, .m1v, .mp2,.mp3, .mpa, .mpe, .m3u, .avi, .asf, .wma, .wmv, .wm.
        /// </summary>
        internal static string VideoFileTypes {
            get {
                return ResourceManager.GetString("VideoFileTypes", resourceCulture);
            }
        }
    }
}
